chore: add skeleton loading
realChakrawarti/yt-catalog pull request #96
Opened 2024-12-27 16:04 UTC by jey-exp

Success full merge will close #16

2024-12-27 16:30 UTC, realChakrawarti commented
@jey-exp Thanks for raising the PR. Could you please re-target to `dev` branch instead of `main`.

2024-12-27 16:35 UTC, jey-exp commented
Sorry, fixed it.

Do you know why "Authorization required to deploy" error is caused?
Is that something I can fix?

2024-12-27 16:40 UTC, realChakrawarti commented
> Sorry, fixed it.
Thanks for updating it. I will update you if any change is required.
 
> Do you know why "Authorization required to deploy" error is caused? Is that something I can fix?
I will have to check, I believe this has to do Vercel's deployment or GitHub rules. If this is something that could be solved from your end I will let you know. 👍🏻

2024-12-28 09:47 UTC, realChakrawarti requested changes
@jey-exp Thanks for raising the PR. 😊

I added couple of comments, could you please address them. If something isn't clear please do let me know.

2024-12-28 09:47 UTC, realChakrawarti commented on src/app/(views)/(public)/c/[catalogId]/RenderPage.tsx
[Blocking] Doing this means the fetching will happen in client (browser) instead of server. Since these are public pages, I want them to be server rendered for SEO & of course to hide the endpoint 😅. 

You can add the skeleton on `loading.tsx`. Refer: https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming while keeping the original code unchanged.

Please use the `GridContainer` component and render boxes by creating a skeleton for the YouTubeCard. 

Something like this,
```tsx
[...Array(10).keys()].map(item => (<YouTubeSkeletonCard key={item} /> ))
```

2024-12-28 09:47 UTC, realChakrawarti commented on src/app/(views)/(public)/a/[archiveId]/RenderPage.tsx
[Blocking] Doing this means the fetching will happen in client (browser) instead of server. Since these are public pages, I want them to be server rendered for SEO & of course to hide the endpoint 😅. 

You can add the skeleton on `loading.tsx`. Refer: https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming while keeping the original code unchanged.

Please use the `GridContainer` component and render boxes by creating a skeleton for the YouTubeCard. 

Something like this,
```tsx
[...Array(10).keys()].map(item => (<YouTubeSkeletonCard key={item} /> ))
```

2024-12-28 13:41 UTC, jey-exp commented on src/app/(views)/(public)/a/[archiveId]/RenderPage.tsx
I get it. Thanks for letting me know

Will revert the changes and implement it as u said.

2024-12-28 13:44 UTC, jey-exp commented on src/components/shadcn/skeleton.tsx
> +      className={cn("animate-pulse rounded-md bg-slate-50 opacity-25", className)}
okay, will increase the opacity only.

2024-12-28 14:32 UTC, jey-exp commented
I have changed them, see if it is fine.

2024-12-28 14:35 UTC, jey-exp commented
It was fun working on this issue, thanks for opening it 👀

2024-12-29 13:33 UTC, realChakrawarti commented
@jey-exp This is nice 🤩! Though there are a few issues with the layout, could please fix them.
### On mobile devices, the card isn't taking up the full width
![image](https://github.com/user-attachments/assets/68925dc3-9def-458a-97e8-c6194f3b6659)

### On certain viewport tablet/desktop devices, cards are overlapping
![image](https://github.com/user-attachments/assets/11fddd90-2d1e-4450-a8e3-c3150c960572)

I have created a branch with changes for the catalog loading: https://github.com/realChakrawarti/yt-catalog/tree/ref-catalog-loading for your reference. 

Please checkout to this branch and check it out once. Could you please replicate the same for the archives page. 

Here is how I implemented this:
- I copied catalog's `page.tsx` to a separate file `loading-skeleton.tsx`.
-  I removed the logic and converted those `div`s which holds content to `Skeleton` component. 
- Checked the classes for font-size (text-xs, text-sm, text-base, text-md ...etc). For the respective font-size, I replaced with the corresponding tailwind height utility class (h-4, h-6 etc). If its an image or something square I used the `size-x` utility class which sets both the width and the height at the same time.
**NOTE:** If you are using tailwindcss extension, you can hover the utility class (text-sm etc) and see the actual pixel and then use that as a reference for the height.
- I compared that with production site for quick reference.   

Here is the commit diff for reference: https://github.com/realChakrawarti/yt-catalog/commit/ab2a18b0e200e1bb74a9414424175ea6bb336af4


Please do let me know if something isn't clear. 😊

2024-12-29 17:55 UTC, jey-exp commented
I have made the changes. 

But seems like when I committed them, my branch was behind the upstream. But I synced the dev branch, made a pull in the local, now rebased my feature branch to dev and then made changes. 
Did I miss something?

2024-12-29 18:02 UTC, jey-exp commented
@realChakrawarti  I am planning to close this PR and raise a new one with cleaner commit history. 

May I do it?

2024-12-29 18:05 UTC, realChakrawarti commented
> @realChakrawarti I am planning to close this PR and raise a new one with cleaner commit history.
> 
> May I do it?

Sure 😊👍🏻

2024-12-29 18:24 UTC, closed without merging